2018-10-30T20:45:47.367-0500 I CONTROL  [initandlisten] MongoDB starting : pid=19356 port=27017 dbpath=/data/db 64-bit host=installminsMBP5
2018-10-30T20:45:47.367-0500 I CONTROL  [initandlisten] db version v4.0.0
2018-10-30T20:45:47.367-0500 I CONTROL  [initandlisten] git version: 3b07af3d4f471ae89e8186d33bbb1d5259597d51
2018-10-30T20:45:47.367-0500 I CONTROL  [initandlisten] allocator: system
2018-10-30T20:45:47.367-0500 I CONTROL  [initandlisten] modules: none
2018-10-30T20:45:47.367-0500 I CONTROL  [initandlisten] build environment:
2018-10-30T20:45:47.367-0500 I CONTROL  [initandlisten]     distarch: x86_64
2018-10-30T20:45:47.368-0500 I CONTROL  [initandlisten]     target_arch: x86_64
2018-10-30T20:45:47.368-0500 I CONTROL  [initandlisten] options: { processManagement: { fork: true }, systemLog: { destination: "file", path: "../../bash/vocab/mongo_log/mongod.log" } }
2018-10-30T20:45:47.368-0500 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-10-30T20:45:47.368-0500 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7680M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-10-30T20:45:48.216-0500 I STORAGE  [initandlisten] WiredTiger message [1540950348:215996][19356:0x7fffc357d3c0], txn-recover: Main recovery loop: starting at 99/8448
2018-10-30T20:45:48.303-0500 I STORAGE  [initandlisten] WiredTiger message [1540950348:303072][19356:0x7fffc357d3c0], txn-recover: Recovering log 99 through 100
2018-10-30T20:45:48.368-0500 I STORAGE  [initandlisten] WiredTiger message [1540950348:367991][19356:0x7fffc357d3c0], txn-recover: Recovering log 100 through 100
2018-10-30T20:45:48.416-0500 I STORAGE  [initandlisten] WiredTiger message [1540950348:416783][19356:0x7fffc357d3c0], txn-recover: Set global recovery timestamp: 0
2018-10-30T20:45:48.536-0500 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2018-10-30T20:45:48.836-0500 I CONTROL  [initandlisten] 
2018-10-30T20:45:48.837-0500 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-10-30T20:45:48.838-0500 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-10-30T20:45:48.838-0500 I CONTROL  [initandlisten] 
2018-10-30T20:45:48.838-0500 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2018-10-30T20:45:48.838-0500 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2018-10-30T20:45:48.839-0500 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2018-10-30T20:45:48.839-0500 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2018-10-30T20:45:48.839-0500 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2018-10-30T20:45:48.839-0500 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2018-10-30T20:45:48.840-0500 I CONTROL  [initandlisten] 
2018-10-30T20:45:48.993-0500 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-10-30T20:45:48.994-0500 I NETWORK  [initandlisten] waiting for connections on port 27017
2018-10-30T20:45:49.725-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58811 #1 (1 connection now open)
2018-10-30T20:45:49.726-0500 I NETWORK  [conn1] received client metadata from 127.0.0.1:58811 conn1: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-30T20:45:50.345-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58814 #2 (2 connections now open)
2018-10-30T20:45:50.345-0500 I NETWORK  [conn2] received client metadata from 127.0.0.1:58814 conn2: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-30T20:46:15.070-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58820 #3 (3 connections now open)
2018-10-30T20:46:15.071-0500 I NETWORK  [conn3] received client metadata from 127.0.0.1:58820 conn3: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-30T20:53:04.447-0500 I NETWORK  [conn3] end connection 127.0.0.1:58820 (2 connections now open)
2018-10-30T20:53:04.447-0500 I NETWORK  [conn2] end connection 127.0.0.1:58814 (1 connection now open)
2018-10-30T20:53:04.770-0500 I NETWORK  [conn1] end connection 127.0.0.1:58811 (0 connections now open)
2018-10-30T20:53:04.829-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58863 #4 (1 connection now open)
2018-10-30T20:53:04.831-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58865 #5 (2 connections now open)
2018-10-30T20:53:04.833-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58867 #6 (3 connections now open)
2018-10-30T20:53:04.834-0500 I NETWORK  [conn4] end connection 127.0.0.1:58863 (2 connections now open)
2018-10-30T20:53:04.834-0500 I NETWORK  [conn5] end connection 127.0.0.1:58865 (1 connection now open)
2018-10-30T20:53:04.834-0500 I NETWORK  [conn6] end connection 127.0.0.1:58867 (0 connections now open)
2018-10-30T20:53:04.852-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58871 #7 (1 connection now open)
2018-10-30T20:53:04.853-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58873 #8 (2 connections now open)
2018-10-30T20:53:04.856-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58875 #9 (3 connections now open)
2018-10-30T20:53:04.857-0500 I NETWORK  [conn8] end connection 127.0.0.1:58873 (1 connection now open)
2018-10-30T20:53:04.857-0500 I NETWORK  [conn7] end connection 127.0.0.1:58871 (2 connections now open)
2018-10-30T20:53:04.857-0500 I NETWORK  [conn9] end connection 127.0.0.1:58875 (0 connections now open)
2018-10-30T20:53:04.877-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58879 #10 (1 connection now open)
2018-10-30T20:53:04.878-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:58881 #11 (2 connections now open)
2018-10-30T20:53:04.881-0500 I NETWORK  [conn10] end connection 127.0.0.1:58879 (1 connection now open)
2018-10-30T20:53:04.881-0500 I NETWORK  [conn11] end connection 127.0.0.1:58881 (0 connections now open)
2018-10-30T20:59:59.149-0500 I CONTROL  [signalProcessingThread] got signal 15 (Terminated: 15), will terminate after current cmd ends
2018-10-30T20:59:59.150-0500 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
2018-10-30T20:59:59.150-0500 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
2018-10-30T20:59:59.150-0500 I CONTROL  [signalProcessingThread] Shutting down free monitoring
2018-10-30T20:59:59.151-0500 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
2018-10-30T20:59:59.152-0500 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
2018-10-30T20:59:59.362-0500 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
2018-10-30T20:59:59.363-0500 I CONTROL  [signalProcessingThread] now exiting
2018-10-30T20:59:59.363-0500 I CONTROL  [signalProcessingThread] shutting down with code:0
