2018-10-27T22:01:38.746-0500 I CONTROL  [initandlisten] MongoDB starting : pid=58107 port=27017 dbpath=/data/db 64-bit host=installminsMBP5
2018-10-27T22:01:38.746-0500 I CONTROL  [initandlisten] db version v4.0.0
2018-10-27T22:01:38.746-0500 I CONTROL  [initandlisten] git version: 3b07af3d4f471ae89e8186d33bbb1d5259597d51
2018-10-27T22:01:38.746-0500 I CONTROL  [initandlisten] allocator: system
2018-10-27T22:01:38.746-0500 I CONTROL  [initandlisten] modules: none
2018-10-27T22:01:38.746-0500 I CONTROL  [initandlisten] build environment:
2018-10-27T22:01:38.746-0500 I CONTROL  [initandlisten]     distarch: x86_64
2018-10-27T22:01:38.747-0500 I CONTROL  [initandlisten]     target_arch: x86_64
2018-10-27T22:01:38.747-0500 I CONTROL  [initandlisten] options: { processManagement: { fork: true }, systemLog: { destination: "file", path: "../../bash/vocab/mongo_log/mongod.log" } }
2018-10-27T22:01:38.748-0500 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-10-27T22:01:38.748-0500 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7680M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-10-27T22:01:39.702-0500 I STORAGE  [initandlisten] WiredTiger message [1540695699:702193][58107:0x7fffa90963c0], txn-recover: Main recovery loop: starting at 95/50816
2018-10-27T22:01:39.794-0500 I STORAGE  [initandlisten] WiredTiger message [1540695699:794927][58107:0x7fffa90963c0], txn-recover: Recovering log 95 through 96
2018-10-27T22:01:39.865-0500 I STORAGE  [initandlisten] WiredTiger message [1540695699:865930][58107:0x7fffa90963c0], txn-recover: Recovering log 96 through 96
2018-10-27T22:01:39.916-0500 I STORAGE  [initandlisten] WiredTiger message [1540695699:916406][58107:0x7fffa90963c0], txn-recover: Set global recovery timestamp: 0
2018-10-27T22:01:40.031-0500 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2018-10-27T22:01:40.425-0500 I CONTROL  [initandlisten] 
2018-10-27T22:01:40.426-0500 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-10-27T22:01:40.426-0500 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-10-27T22:01:40.426-0500 I CONTROL  [initandlisten] 
2018-10-27T22:01:40.426-0500 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2018-10-27T22:01:40.427-0500 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2018-10-27T22:01:40.427-0500 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2018-10-27T22:01:40.427-0500 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2018-10-27T22:01:40.427-0500 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2018-10-27T22:01:40.428-0500 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2018-10-27T22:01:40.428-0500 I CONTROL  [initandlisten] 
2018-10-27T22:01:40.601-0500 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-10-27T22:01:40.603-0500 I NETWORK  [initandlisten] waiting for connections on port 27017
2018-10-27T22:01:41.645-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:57460 #1 (1 connection now open)
2018-10-27T22:01:41.646-0500 I NETWORK  [conn1] received client metadata from 127.0.0.1:57460 conn1: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-27T22:01:42.218-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:57461 #2 (2 connections now open)
2018-10-27T22:01:42.219-0500 I NETWORK  [conn2] received client metadata from 127.0.0.1:57461 conn2: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-27T22:02:19.663-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:57480 #3 (3 connections now open)
2018-10-27T22:02:19.664-0500 I NETWORK  [conn3] received client metadata from 127.0.0.1:57480 conn3: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-27T22:07:31.132-0500 I NETWORK  [conn3] end connection 127.0.0.1:57480 (2 connections now open)
2018-10-27T22:07:31.132-0500 I NETWORK  [conn2] end connection 127.0.0.1:57461 (1 connection now open)
2018-10-27T22:07:31.584-0500 I NETWORK  [conn1] end connection 127.0.0.1:57460 (0 connections now open)
2018-10-27T22:07:31.669-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:57506 #4 (1 connection now open)
2018-10-27T22:07:31.670-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:57508 #5 (2 connections now open)
2018-10-27T22:07:31.674-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:57510 #6 (3 connections now open)
2018-10-27T22:07:31.676-0500 I NETWORK  [conn4] end connection 127.0.0.1:57506 (2 connections now open)
2018-10-27T22:07:31.676-0500 I NETWORK  [conn5] end connection 127.0.0.1:57508 (1 connection now open)
2018-10-27T22:07:31.676-0500 I NETWORK  [conn6] end connection 127.0.0.1:57510 (0 connections now open)
2018-10-27T22:07:31.697-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:57514 #7 (1 connection now open)
2018-10-27T22:07:31.699-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:57516 #8 (2 connections now open)
2018-10-27T22:07:31.701-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:57518 #9 (3 connections now open)
2018-10-27T22:07:31.703-0500 I NETWORK  [conn7] end connection 127.0.0.1:57514 (2 connections now open)
2018-10-27T22:07:31.703-0500 I NETWORK  [conn9] end connection 127.0.0.1:57518 (1 connection now open)
2018-10-27T22:07:31.703-0500 I NETWORK  [conn8] end connection 127.0.0.1:57516 (0 connections now open)
2018-10-27T22:07:31.723-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:57522 #10 (1 connection now open)
2018-10-27T22:07:31.725-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:57524 #11 (2 connections now open)
2018-10-27T22:07:31.729-0500 I NETWORK  [conn10] end connection 127.0.0.1:57522 (1 connection now open)
2018-10-27T22:07:31.729-0500 I NETWORK  [conn11] end connection 127.0.0.1:57524 (0 connections now open)
2018-10-27T22:07:35.465-0500 I CONTROL  [signalProcessingThread] got signal 15 (Terminated: 15), will terminate after current cmd ends
2018-10-27T22:07:35.465-0500 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
2018-10-27T22:07:35.465-0500 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
2018-10-27T22:07:35.466-0500 I CONTROL  [signalProcessingThread] Shutting down free monitoring
2018-10-27T22:07:35.466-0500 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
2018-10-27T22:07:35.468-0500 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
2018-10-27T22:07:35.717-0500 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
2018-10-27T22:07:35.719-0500 I CONTROL  [signalProcessingThread] now exiting
2018-10-27T22:07:35.719-0500 I CONTROL  [signalProcessingThread] shutting down with code:0
