2018-10-15T15:50:49.548-0500 I CONTROL  [initandlisten] MongoDB starting : pid=56767 port=27017 dbpath=/data/db 64-bit host=installminsMBP5
2018-10-15T15:50:49.548-0500 I CONTROL  [initandlisten] db version v4.0.0
2018-10-15T15:50:49.548-0500 I CONTROL  [initandlisten] git version: 3b07af3d4f471ae89e8186d33bbb1d5259597d51
2018-10-15T15:50:49.549-0500 I CONTROL  [initandlisten] allocator: system
2018-10-15T15:50:49.549-0500 I CONTROL  [initandlisten] modules: none
2018-10-15T15:50:49.549-0500 I CONTROL  [initandlisten] build environment:
2018-10-15T15:50:49.549-0500 I CONTROL  [initandlisten]     distarch: x86_64
2018-10-15T15:50:49.549-0500 I CONTROL  [initandlisten]     target_arch: x86_64
2018-10-15T15:50:49.549-0500 I CONTROL  [initandlisten] options: { processManagement: { fork: true }, systemLog: { destination: "file", path: "../../bash/vocab/mongo_log/mongod.log" } }
2018-10-15T15:50:49.551-0500 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-10-15T15:50:49.552-0500 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7680M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-10-15T15:50:50.456-0500 I STORAGE  [initandlisten] WiredTiger message [1539636650:456491][56767:0x7fffc4d0c3c0], txn-recover: Main recovery loop: starting at 76/8448
2018-10-15T15:50:50.556-0500 I STORAGE  [initandlisten] WiredTiger message [1539636650:556101][56767:0x7fffc4d0c3c0], txn-recover: Recovering log 76 through 77
2018-10-15T15:50:50.626-0500 I STORAGE  [initandlisten] WiredTiger message [1539636650:626017][56767:0x7fffc4d0c3c0], txn-recover: Recovering log 77 through 77
2018-10-15T15:50:50.673-0500 I STORAGE  [initandlisten] WiredTiger message [1539636650:673596][56767:0x7fffc4d0c3c0], txn-recover: Set global recovery timestamp: 0
2018-10-15T15:50:50.791-0500 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2018-10-15T15:50:51.149-0500 I CONTROL  [initandlisten] 
2018-10-15T15:50:51.149-0500 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-10-15T15:50:51.150-0500 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-10-15T15:50:51.150-0500 I CONTROL  [initandlisten] 
2018-10-15T15:50:51.150-0500 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2018-10-15T15:50:51.150-0500 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2018-10-15T15:50:51.151-0500 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2018-10-15T15:50:51.151-0500 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2018-10-15T15:50:51.152-0500 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2018-10-15T15:50:51.152-0500 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2018-10-15T15:50:51.152-0500 I CONTROL  [initandlisten] 
2018-10-15T15:50:51.322-0500 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-10-15T15:50:51.325-0500 I NETWORK  [initandlisten] waiting for connections on port 27017
2018-10-15T15:50:52.373-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:63985 #1 (1 connection now open)
2018-10-15T15:50:52.374-0500 I NETWORK  [conn1] received client metadata from 127.0.0.1:63985 conn1: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-15T15:50:52.906-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:63986 #2 (2 connections now open)
2018-10-15T15:50:52.906-0500 I NETWORK  [conn2] received client metadata from 127.0.0.1:63986 conn2: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-15T15:55:12.705-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:64017 #3 (3 connections now open)
2018-10-15T15:55:12.706-0500 I NETWORK  [conn3] received client metadata from 127.0.0.1:64017 conn3: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-10-15T16:01:56.049-0500 I NETWORK  [conn3] end connection 127.0.0.1:64017 (1 connection now open)
2018-10-15T16:01:56.049-0500 I NETWORK  [conn2] end connection 127.0.0.1:63986 (2 connections now open)
2018-10-15T16:01:56.211-0500 I NETWORK  [conn1] end connection 127.0.0.1:63985 (0 connections now open)
2018-10-15T16:01:56.308-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:64048 #4 (1 connection now open)
2018-10-15T16:01:56.309-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:64050 #5 (2 connections now open)
2018-10-15T16:01:56.313-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:64052 #6 (3 connections now open)
2018-10-15T16:01:56.316-0500 I NETWORK  [conn4] end connection 127.0.0.1:64048 (2 connections now open)
2018-10-15T16:01:56.316-0500 I NETWORK  [conn5] end connection 127.0.0.1:64050 (1 connection now open)
2018-10-15T16:01:56.316-0500 I NETWORK  [conn6] end connection 127.0.0.1:64052 (0 connections now open)
2018-10-15T16:01:56.334-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:64056 #7 (1 connection now open)
2018-10-15T16:01:56.335-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:64058 #8 (2 connections now open)
2018-10-15T16:01:56.338-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:64060 #9 (3 connections now open)
2018-10-15T16:01:56.340-0500 I NETWORK  [conn7] end connection 127.0.0.1:64056 (2 connections now open)
2018-10-15T16:01:56.340-0500 I NETWORK  [conn8] end connection 127.0.0.1:64058 (1 connection now open)
2018-10-15T16:01:56.340-0500 I NETWORK  [conn9] end connection 127.0.0.1:64060 (0 connections now open)
2018-10-15T16:01:56.361-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:64064 #10 (1 connection now open)
2018-10-15T16:01:56.364-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:64066 #11 (2 connections now open)
2018-10-15T16:01:56.366-0500 I NETWORK  [conn10] end connection 127.0.0.1:64064 (1 connection now open)
2018-10-15T16:01:56.366-0500 I NETWORK  [conn11] end connection 127.0.0.1:64066 (0 connections now open)
2018-10-15T16:02:02.347-0500 I CONTROL  [signalProcessingThread] got signal 15 (Terminated: 15), will terminate after current cmd ends
2018-10-15T16:02:02.348-0500 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
2018-10-15T16:02:02.348-0500 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
2018-10-15T16:02:02.348-0500 I CONTROL  [signalProcessingThread] Shutting down free monitoring
2018-10-15T16:02:02.348-0500 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
2018-10-15T16:02:02.350-0500 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
2018-10-15T16:02:02.544-0500 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
2018-10-15T16:02:02.545-0500 I CONTROL  [signalProcessingThread] now exiting
2018-10-15T16:02:02.546-0500 I CONTROL  [signalProcessingThread] shutting down with code:0
